version: "3.3"

services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    volumes:
      - config:/app/config # Make sure your local config directory exists
      # - /var/run/docker.sock:/var/run/docker.sock:ro # Mounted as read-only
    networks:
      - traefik-public
      - homepage-network
    deploy:
      placement:
        constraints:
          - node.hostname == orangepi-2
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public

        - traefik.http.routers.homepage-http.rule=Host(`services.home.dalenw.com`)
        - traefik.http.routers.homepage-http.entrypoints=http
        - traefik.http.routers.homepage-http.middlewares=https-redirect

        - traefik.http.routers.homepage-https.rule=Host(`services.home.dalenw.com`)
        - traefik.http.routers.homepage-https.entrypoints=https
        - traefik.http.routers.homepage-https.tls=true
        - traefik.http.routers.homepage-https.tls.certresolver=le
        
        - traefik.http.services.homepage.loadbalancer.server.port=3000
  
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    # container_name: dockerproxy
    networks:
      - homepage-network
    environment:
        - CONTAINERS=1 # Allow access to viewing containers
        - POST=0 # Disallow any POST operations (effectively read-only)
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro # Mounted as read-only
    restart: unless-stopped

volumes:
  config:
    driver: local

networks:
  traefik-public:
    external: true
  homepage-network:
    driver: overlay