version: "3.9"

services:
  app:
    image: nextcloud:latest
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

      REDIS_HOST: redis
      REDIS_HOST_PASSWORD: ${REDIS_HOST_PASSWORD}

      # OBJECTSTORE_S3_HOST: minio1
      # OBJECTSTORE_S3_BUCKET: nextcloud
      # OBJECTSTORE_S3_KEY: ${OBJECTSTORE_S3_KEY}
      # OBJECTSTORE_S3_SECRET: ${OBJECTSTORE_S3_SECRET}
      # OBJECTSTORE_S3_SSL: "false"
      # OBJECTSTORE_S3_PORT: 9000

      NEXTCLOUD_TRUSTED_DOMAINS: "nextcloud.dalenw.com"
    restart: unless-stopped
    depends_on:
      - db
      - redis
    networks:
      - nextcloud-net
      - traefik-public
    volumes:
      - nextcloud:/var/www/html:rw
    deploy:
      placement:
        constraints:
          - node.hostname == orangepi-6
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.nextcloud-http.rule=Host(`nextcloud.home.dalenw.com`,`nextcloud.dalenw.com`)
        - traefik.http.routers.nextcloud-http.entrypoints=http
        - traefik.http.routers.nextcloud-http.middlewares=https-redirect
        - traefik.http.routers.nextcloud-https.rule=Host(`nextcloud.home.dalenw.com`,`nextcloud.dalenw.com`)
        - traefik.http.routers.nextcloud-https.entrypoints=https
        - traefik.http.routers.nextcloud-https.tls=true
        - traefik.http.routers.nextcloud-https.tls.certresolver=le
        - traefik.http.services.nextcloud.loadbalancer.server.port=80

        - traefik.http.routers.nextcloud-https.middlewares=nextcloud_redirectregex
        - traefik.http.middlewares.nextcloud_redirectregex.redirectregex.permanent=true
        - traefik.http.middlewares.nextcloud_redirectregex.redirectregex.regex="https://(.*)/.well-known/(?:card|cal)dav"
        - traefik.http.middlewares.nextcloud_redirectregex.redirectregex.replacement="https://$${1}/remote.php/dav"

  db:
    image: mariadb:10
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb_read_only_compressed=OFF
    environment:
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PWD: ${MYSQL_PASSWORD}
    restart: unless-stopped
    networks:
      - nextcloud-net
    volumes: 
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      placement:
        constraints:
          - node.hostname == orangepi-6

  # web:
  #   image: nginx
  #   restart: unless-stopped
  #   links:
  #     - nc
  #   volumes:
  #     - nginx-conf:/etc/nginx/
  #     - nextcloud:/var/www/html:ro
  #   networks:
  #     - nextcloud-net
  #     - traefik-public
  #   deploy:
  #     placement:
  #       constraints:
  #         - node.hostname == orangepi-6
  #     labels:
  #       - traefik.enable=true
  #       - traefik.docker.network=traefik-public
  #       - traefik.constraint-label=traefik-public
  #       - traefik.http.routers.nextcloud-http.rule=Host(`nextcloud.home.dalenw.com`,`nextcloud.dalenw.com`)
  #       - traefik.http.routers.nextcloud-http.entrypoints=http
  #       - traefik.http.routers.nextcloud-http.middlewares=https-redirect
  #       - traefik.http.routers.nextcloud-https.rule=Host(`nextcloud.home.dalenw.com`,`nextcloud.dalenw.com`)
  #       - traefik.http.routers.nextcloud-https.entrypoints=https
  #       - traefik.http.routers.nextcloud-https.tls=true
  #       - traefik.http.routers.nextcloud-https.tls.certresolver=le
  #       - traefik.http.services.nextcloud.loadbalancer.server.port=80

  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - nextcloud-net
    command: redis-server --requirepass ${REDIS_HOST_PASSWORD}

volumes:
  db-data:
    driver: local
  nginx-conf:
    driver: local
  nextcloud:
    driver: local

networks:
  nextcloud-net:
    driver: overlay
  traefik-public:
    external: true