version: '3.3'

services:
  registry:
    image: registry:latest 
    restart: always
    ports:
      - "5000:5000"
    networks:
      - traefik-public
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data 
    volumes:
      - registry-data:/data 
    deploy:
      placement:
        constraints:
          - node.hostname == orangepi-1
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.registry-http.rule=Host(`registry.home.dalenw.com`)
        - traefik.http.routers.registry-http.entrypoints=http
        - traefik.http.routers.registry-http.middlewares=https-redirect
        - traefik.http.routers.registry-https.rule=Host(`registry.home.dalenw.com`)
        - traefik.http.routers.registry-https.entrypoints=https
        - traefik.http.routers.registry-https.tls=true
        - traefik.http.routers.registry-https.tls.certresolver=le
        - traefik.http.services.registry.loadbalancer.server.port=5000

networks:
  traefik-public:
    external: true
